完善了UserServiceImp的部分业务逻辑
whpu-aa/website pull request #107
Opened 2021-05-23 08:36 UTC by eternal-fy

1.由于UserRepository的方法一部分实现了接口，但是接口中的方法有些不满足要求，还有许多的增加的功能没实现，于是增加了UserMapper接口。这个接口全部复制于UserService的接口，但是为了实现功能添加了几个其他的方法。
2.为了测试方便，新增加了一个测试类，并且有些实体类实现了toString()方法。

2021-05-24 13:30 UTC, crupest requested changes

2021-05-24 13:30 UTC, crupest commented on BackEnd/build.gradle
> +    implementation group: 'org.mybatis.spring.boot', name: 'mybatis-spring-boot-starter', version: '1.3.2'
统一格式
```suggestion
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter'
```

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/java/whpuaa/website/user/UserInfo.java
> +    public UserInfo(){}
不要加这个构造函数，不要在mapper里使用这个类。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/java/whpuaa/website/user/UserMapper.java
> +package whpuaa.website.user;
重新设计一下mapper类：
1. 全部使用User作为entity。
2. 接口重新设计成纯数据库的接口，多余的接口和throws声明都删掉。
3. 文档删掉。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/java/whpuaa/website/user/UserService.java
> +    List<UserInfo> getUsers(long page, long numberPerPage) throws UserNotExistException;
这个函数为什么会抛`UserNotExistException`呢，没用户就返回空列表啊。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/java/whpuaa/website/user/UserServiceImpl.java
> +       return userMapper.getUserId(username);
mapper改了之后，用我写的那个map函数来进行转化。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/java/whpuaa/website/user/UserServiceImpl.java
> +        User user = userMapper.getUserById(id);
同上。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/java/whpuaa/website/user/UserServiceImpl.java
> -        return null;
同上。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/java/whpuaa/website/user/UserServiceImpl.java
> +        UserInfo user = getUser(id);
你这怎么个modify法，是不是没写完。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/java/whpuaa/website/user/UserServiceImpl.java
> +        if(null==ans)
这里是与null比较还是和0比较查一下文档。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/java/whpuaa/website/user/UserServiceImpl.java
> +        if(ans>1)
这个地方的逻辑是判断`id`是不是1，是1说明删的是root用户，就抛出这个异常。ans不可能大于1，因为不可能用相同的id。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/java/whpuaa/website/user/UserServiceImpl.java
> +        if(user.getPassword().equals(password))
密码不是这么检查的，用`passwordEncoder.matches`。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/resources/application.properties
> +mybatis.type-aliases-package=whpuaa.website.user
这个`mybatis.type-aliases-package`是干嘛的。。。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/resources/mapper/UserMapper.xml
> +       select *
这里看看能不能来个联表查询，把permission和detail一并查了

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/resources/mapper/UserMapper.xml
> +     <select id="getIdByUsername" resultType="long">
这个和`getUserId`不一样吗。。。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/main/resources/mapper/UserMapper.xml
> +        limit (#{page}-1)*#{numberPerPage},#{numberPerPage}
好像不是这么写sql的吧。

2021-05-24 13:30 UTC, crupest commented on BackEnd/src/test/java/whpuaa/website/ServiceImpTest.java
> +package whpuaa.website;
test命名清楚一点，测的啥。

2021-05-25 13:19 UTC, eternal-fy commented on BackEnd/build.gradle
> +    implementation group: 'org.mybatis.spring.boot', name: 'mybatis-spring-boot-starter', version: '1.3.2'
![image](https://user-images.githubusercontent.com/69158640/119504721-d28efa00-bd9e-11eb-8f53-e2f77d580e19.png)
改了就找不到

2021-05-25 13:21 UTC, crupest commented on BackEnd/build.gradle
> +    implementation group: 'org.mybatis.spring.boot', name: 'mybatis-spring-boot-starter', version: '1.3.2'
那先放着吧，我到时候试试

2021-05-25 14:33 UTC, eternal-fy commented on BackEnd/src/main/resources/application.properties
> +mybatis.type-aliases-package=whpuaa.website.user
用来取别名的，因为mybatis注释里面的文件需要全限类名，为了方便把前面的包名加上去。

2021-05-25 14:36 UTC, eternal-fy commented on BackEnd/src/main/resources/mapper/UserMapper.xml
> +       select *
由于detail是Map类型，这个在mybatis中只能映射map中只有一个键值对。如果想映射多个键值对，就得用List<Map>,也就是说一次是映射不了的。

2021-05-25 14:36 UTC, eternal-fy commented on BackEnd/src/main/resources/mapper/UserMapper.xml
> +     <select id="getIdByUsername" resultType="long">
删了

2021-05-25 14:37 UTC, eternal-fy commented on BackEnd/src/main/resources/mapper/UserMapper.xml
> +        limit (#{page}-1)*#{numberPerPage},#{numberPerPage}
把上面*改成id了

2021-05-25 14:37 UTC, crupest commented on BackEnd/src/main/resources/application.properties
> +mybatis.type-aliases-package=whpuaa.website.user
问题来了，那如果我现在加了`whpuaa.website.token.entity.UserToken`该怎么办，虽然我没用mybatis。

2021-05-25 14:37 UTC, eternal-fy commented on BackEnd/src/main/java/whpuaa/website/user/UserServiceImpl.java
> +       return userMapper.getUserId(username);
ok

2021-05-25 14:38 UTC, eternal-fy commented on BackEnd/src/main/java/whpuaa/website/user/UserService.java
> +    List<UserInfo> getUsers(long page, long numberPerPage) throws UserNotExistException;
ok,删了声明

2021-05-25 14:51 UTC, crupest commented on BackEnd/src/main/resources/mapper/UserMapper.xml
> +        limit (#{page}-1)*#{numberPerPage},#{numberPerPage}
不是我是说这个limit是咋写的。。。

2021-05-25 14:54 UTC, eternal-fy commented on BackEnd/src/main/resources/application.properties
> +mybatis.type-aliases-package=whpuaa.website.user
再加一个包名上去，和这个一样。那个如果找不到，就会在设置的类路径下去找。当然你不嫌麻烦也可以用全限类名。优先找你自己写的类名，找不到才到设置别名那儿去找。

2021-05-25 14:58 UTC, eternal-fy commented on BackEnd/src/main/resources/mapper/UserMapper.xml
> +        limit (#{page}-1)*#{numberPerPage},#{numberPerPage}
limit  offset，num        offset表示要查找的开始下标（从0开始算）  ，nums是要查询的个数    比如第一页，一页五个数字，就是从0开始算，num=5    查到了0 1 2 3 4。   查第二页，那么就是 从下标5开始算。这个就是一个数学表达式。

2021-05-28 08:29 UTC, closed without merging