完成了nav元素的更改，About页面的修改
whpu-aa/website pull request #110
Opened 2021-05-25 12:35 UTC by jeffyangcoder

# 完成了nav元素的更改，About页面的修改
### 也就是柳学长布置的步骤一和步骤二
#### AppBar部分的代码我可能写的还不太行，我先提交一个版本，后续有新的改进我再提交，目前只是勉强实现了该有的功能
@liu839

2021-05-25 14:13 UTC, liu839 requested changes

2021-05-25 14:13 UTC, liu839 commented on FrontEnd/src/components/AppBar.vue
> +  <div class="nav">
语义化标签不是更好吗?这是为何?

2021-05-25 14:13 UTC, liu839 commented on FrontEnd/src/components/AppBar.vue
> +  </div>
搞错了搞错了,不改动这个页面呀!!

2021-05-25 14:13 UTC, liu839 commented on FrontEnd/src/views/About.vue
>          </el-select></h1
你去查查上面这个是啥,看能不能把这个展开成tab,就appbar那样

2021-05-26 06:46 UTC, jeffyangcoder commented
@liu839 已经改正了，看看是这个意思对吗

2021-05-26 14:59 UTC, jeffyangcoder commented
# 本次PR修改了About页面的选择器展示
1.将选择器选择展示换成标签页展示,为顶居中
* ![image](https://user-images.githubusercontent.com/55988379/119682631-9f6b6a00-be75-11eb-93d7-7a80abefba7c.png) 

2. 完成了整体的逻辑合并
* ![image](https://user-images.githubusercontent.com/55988379/119683027-ec4f4080-be75-11eb-80e9-0ba4194e6eca.png)
* ![image](https://user-images.githubusercontent.com/55988379/119683098-f8d39900-be75-11eb-8579-bfbfb8afef1b.png)

2021-05-26 15:11 UTC, liu839 submitted a review, later dismissed
干的漂亮!

2021-05-27 07:46 UTC, liu839 approved these changes

2021-05-27 07:47 UTC, merged