添加了部门介绍组件，增加了相关的图片在assets文件的group_pic文件夹中
whpu-aa/website pull request #20
Opened 2020-08-19 15:27 UTC by eternal-fy

就单独弄了个粗糙页面，看看能不能导入,我把内容弄成了export default

2020-08-19 15:59 UTC, crupest requested changes
用vetur插件格式化代码后提交。

2020-08-19 15:59 UTC, crupest commented on src/App.vue
> -
撤回这个更改，不要提交无意义的空行删减以防止历史记录混乱。

2020-08-19 15:59 UTC, crupest commented on src/views/About.vue
> +
撤回这个更改，不要提交无意义的空行删减以防止历史记录混乱。

2020-08-19 15:59 UTC, crupest commented on src/views/Home.vue
> -
撤回这个更改，不要提交无意义的空行删减以防止历史记录混乱。

2020-08-19 15:59 UTC, crupest commented on src/components/group_introduce.vue
> +  name:group,
此处使用了未定义的变量导致CI未通过。加上引号。
建议改为`group-page`。

2020-08-19 15:59 UTC, crupest commented on src/components/group_introduce.vue
> +    <!--上方栏-->
去掉顶栏，因为已经有一个了。

2020-08-19 15:59 UTC, crupest commented on src/components/group_introduce.vue
> +   <style  >
添加`scoped`让css只局部生效。
删掉所有与顶栏相关的无用的css。

2020-08-20 06:02 UTC, crupest requested changes

2020-08-20 06:02 UTC, crupest commented on src/components/group_introduce.vue
> +  float: left;
最好使用CSS Flexbox来排版，不要用float，不过你可以暂时不改。

2020-08-20 06:02 UTC, crupest commented on src/components/group_introduce.vue
> +  float: left;
同上，最好使用CSS Flexbox来排版，不要用float，不过你可以暂时不改。

2020-08-20 06:02 UTC, crupest commented on src/components/group_introduce.vue
> +    <div class="left" name="left" id="left">
`name`和`id`好像没有用，为了防止冲突，最好删掉。

2020-08-20 06:11 UTC, crupest requested changes
将文件`group_introduce.vue`改成`GroupIntroduce.vue`，并将其移动到`views`文件夹，因为它是个页面。

2020-08-20 06:11 UTC, crupest commented on src/components/group_introduce.vue
> +  name: "group_page",
改成PascalCase，即`GroupPage`。

2020-08-20 06:24 UTC, eternal-fy commented on src/components/group_introduce.vue
> +  display: table;
用来显示bgbody这个classdiv区域的背景

2020-08-20 08:30 UTC, crupest approved these changes
EIO!

2020-08-20 08:30 UTC, merged