增加可用来跳转的组件，组件内容为图片加文本。修改新闻文章组件中部分样式并添加其他新闻部分
whpu-aa/website pull request #27
Opened 2020-08-23 14:28 UTC by WithBQ

2020-08-23 17:29 UTC, crupest requested changes

2020-08-23 17:29 UTC, crupest commented on src/components/Skip.vue
> +  name: "Skip",
呃，那所有的超链接都是跳转。。。
我觉得可以改成`MoreArticleItem`

2020-08-23 17:36 UTC, WithBQ commented on src/components/Skip.vue
> +  name: "Skip",
有道理😂😂，明天我把这个改一下

2020-08-24 10:50 UTC, crupest approved these changes

2020-08-24 10:50 UTC, merged