更改了部门介绍的样式，完善了GroupDetail组件和其中的样式。
whpu-aa/website pull request #39
Opened 2020-09-03 15:35 UTC by Mamba-ZJP

2020-09-03 15:43 UTC, Mamba-ZJP commented
更改了部门介绍的样式，完善了GroupDetail组件和其中的样式。

2020-09-04 11:41 UTC, crupest requested changes

2020-09-04 11:41 UTC, crupest commented on src/views/GroupIntroduce.vue
> +  methods: {},
这两行没用的删掉。

2020-09-04 11:41 UTC, crupest commented on src/components/GroupDetail.vue
> +  props: ["index"],
还原这两行。

2020-09-05 02:27 UTC, liu839 requested changes
风格统一，按要求修改

2020-09-05 02:27 UTC, liu839 commented on src/views/GroupIntroduce.vue
>    box-shadow: 10px 10px 5px rgb(106, 106, 245);
阴影形式统一，按照 element 内部统一风格（[链接](https://element.eleme.cn/#/zh-CN/component/border)）
![image](https://user-images.githubusercontent.com/64195205/92295886-904c3100-ef61-11ea-9873-5e73ef385913.png)

2020-09-05 02:27 UTC, liu839 commented on src/views/GroupIntroduce.vue
>    border-radius: 10px;
圆角注意风格统一，按element内部统一，后续记得发一张预览图

2020-09-05 02:27 UTC, liu839 commented on src/views/GroupIntroduce.vue
>    border-radius: 25px;
同上

2020-09-05 14:52 UTC, crupest approved these changes

2020-09-06 02:34 UTC, liu839 approved these changes

2020-09-06 07:29 UTC, merged