新闻页面优化
whpu-aa/website pull request #40
Opened 2020-09-05 04:10 UTC by liu839

界面优化
![image](https://user-images.githubusercontent.com/64195205/92297329-ca70ff00-ef70-11ea-9ced-5037ba9d6f35.png)

2020-09-05 08:50 UTC, WithBQ approved these changes

2020-09-05 08:50 UTC, WithBQ approved these changes

2020-09-05 15:17 UTC, crupest requested changes

2020-09-05 15:17 UTC, crupest commented on src/views/News.vue
> +        <transition-group appear="True" name="el-fade-in">
```suggestion
        <transition-group appear name="el-fade-in">
```
`appear`不用赋值。就算要赋值，因为它是个`boolean`，也应该写成`:appear="true"`。

2020-09-05 15:17 UTC, crupest commented on src/views/News.vue
> +      return id;
这个函数为什么会有返回值呢？如果仅仅只是想填个坑，防止lint错误，可以写`void(0);`再加个注释。

2020-09-05 15:17 UTC, crupest commented on src/views/News.vue
>    display: flex;
```suggestion
```
这一行之前没仔细看。可以删掉。因为库自己已经设置了。

2020-09-05 15:17 UTC, crupest commented on src/views/News.vue
> +  height: 100%;
```suggestion
```
这一行没啥用好像。。。

2020-09-05 15:17 UTC, crupest commented on src/views/News.vue
>  .main {
这个 class 大概可以删掉了，如果下面两行都要删掉的话。记得也删掉html里的。

2020-09-05 15:17 UTC, crupest commented on src/views/News.vue
> +* {
字体最好全局设置。。。

2020-09-05 15:17 UTC, crupest commented on src/views/News.vue
> +.el-main {
我建议把`main`里面的`a`都改成`display: block;`，不要滥用`flex`。
而且我不太推荐你直接使用`el-main`，因为这有点像是实现细节，万一他以后改了呢（虽然不太可能会改）。我建议自己搞个class。

2020-09-05 15:17 UTC, crupest commented on src/views/News.vue
> +.el-aside {
同上

2020-09-06 02:11 UTC, liu839 commented on src/views/News.vue
> +        <transition-group appear="True" name="el-fade-in">
已处理

2020-09-06 02:11 UTC, liu839 commented on src/views/News.vue
> +      return id;
使用`// eslint-disable-next-line no-unused-vars`暂时忽略lint错误

2020-09-06 02:12 UTC, liu839 commented on src/views/News.vue
>  .main {
完成修改

2020-09-06 02:25 UTC, liu839 commented on src/views/News.vue
> +.el-main {
**1. 使用block会挤在一起,  暂时未知原因，正在寻找处理方法**
![image](https://user-images.githubusercontent.com/64195205/92316768-1da78800-f02b-11ea-9bea-276abd378a20.png)


2. 内部可以使用多个`el-main`,作为显示文章预览区域，占一个绝对没问题。后续若有需要可以用`<el-container>`再次包含

2020-09-06 02:28 UTC, liu839 commented on src/views/News.vue
> +.el-main {
`el-main`内部已修改

2020-09-06 02:31 UTC, liu839 commented on src/views/News.vue
> +.el-aside {
同上

2020-09-06 12:27 UTC, crupest requested changes

2020-09-06 12:27 UTC, crupest commented on src/views/News.vue
> +.el-main {
我是说把子元素设置`display:block;`，不是容器元素。
我的意思是`el-main`这个class是Element的实现细节，建议自己定义一个class。

2020-09-06 12:27 UTC, crupest commented on src/views/News.vue
> +* {
使用全局设置的字体。如果你想修改全局字体，再另外提一个pr。

2020-09-06 12:27 UTC, crupest commented on src/views/News.vue
> +.el-aside {
同上

2020-09-06 12:37 UTC, liu839 reviewed
对el布局组件使用有异议，其余按标准修改

2020-09-06 12:37 UTC, liu839 commented on src/views/News.vue
> +.el-main {
这个是element的布局来着？这个能否解释下为何不直接采用这种形式而要另设class呢？

2020-09-06 12:49 UTC, liu839 commented
对规避组件的意见
![image](https://user-images.githubusercontent.com/64195205/92326133-65a5c980-f082-11ea-814b-27cf85130e2d.png)

2020-09-07 02:22 UTC, crupest approved these changes

2020-09-07 02:27 UTC, merged