Liu login
whpu-aa/website pull request #96
Opened 2021-05-19 01:53 UTC by liu839

### 添加login基础页面

2021-05-20 14:18 UTC, crupest requested changes

2021-05-20 14:18 UTC, crupest commented on FrontEnd/package.json
> +    "chokidar": "^2.1.8",
加这个依赖干嘛

2021-05-20 14:18 UTC, crupest commented on FrontEnd/src/router/index.js
> +      import(/* webpackChunkName: "showCode" */ "../views/Login.vue"),
`webChunkName`的值更新一下。

2021-05-20 14:18 UTC, crupest commented on FrontEnd/src/router/index.js
> +      import(/* webpackChunkName: "showCode" */ "../views/SignUp.vue"),
同上

2021-05-21 00:59 UTC, liu839 commented on FrontEnd/src/router/index.js
> +      import(/* webpackChunkName: "showCode" */ "../views/Login.vue"),
### finished

2021-05-21 01:00 UTC, liu839 commented on FrontEnd/package.json
> +    "chokidar": "^2.1.8",
已删除,这不是我手动加的,我以为有了新的依赖

2021-05-21 07:22 UTC, crupest approved these changes

2021-05-21 07:22 UTC, merged